version: "3.9"

services:
  db:
    image: postgres:15
    container_name: credit_db
    restart: always
    environment:
      POSTGRES_DB: credit_system
      POSTGRES_USER: credit_user
      POSTGRES_PASSWORD: credit_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
