# Generated by Django 5.2.6 on 2025-09-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_limit', models.BigIntegerField()),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenure_months', models.PositiveIntegerField()),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('emIs_paid_on_time', models.PositiveIntegerField(default=0)),
                ('total_emis', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.customer')),
            ],
        ),
    ]
